//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntryApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OFFER_FLYER", Namespace="http://schemas.datacontract.org/2004/07/DataEntryDAL.DataAccessLogic")]
    [System.SerializableAttribute()]
    internal partial class OFFER_FLYER : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ADMIN_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DATE_FROMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DATE_TOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> FLYER_APPROVEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> FLYER_EXPIREDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FLYER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FLYER_IMAGE_URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FLYER_NAME_ARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FLYER_NAME_ENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FRAME_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OFFER_TYPE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PROVIDER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int USER_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> ADMIN_ID {
            get {
                return this.ADMIN_IDField;
            }
            set {
                if ((this.ADMIN_IDField.Equals(value) != true)) {
                    this.ADMIN_IDField = value;
                    this.RaisePropertyChanged("ADMIN_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> DATE_FROM {
            get {
                return this.DATE_FROMField;
            }
            set {
                if ((this.DATE_FROMField.Equals(value) != true)) {
                    this.DATE_FROMField = value;
                    this.RaisePropertyChanged("DATE_FROM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> DATE_TO {
            get {
                return this.DATE_TOField;
            }
            set {
                if ((this.DATE_TOField.Equals(value) != true)) {
                    this.DATE_TOField = value;
                    this.RaisePropertyChanged("DATE_TO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<bool> FLYER_APPROVED {
            get {
                return this.FLYER_APPROVEDField;
            }
            set {
                if ((this.FLYER_APPROVEDField.Equals(value) != true)) {
                    this.FLYER_APPROVEDField = value;
                    this.RaisePropertyChanged("FLYER_APPROVED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<bool> FLYER_EXPIRED {
            get {
                return this.FLYER_EXPIREDField;
            }
            set {
                if ((this.FLYER_EXPIREDField.Equals(value) != true)) {
                    this.FLYER_EXPIREDField = value;
                    this.RaisePropertyChanged("FLYER_EXPIRED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int FLYER_ID {
            get {
                return this.FLYER_IDField;
            }
            set {
                if ((this.FLYER_IDField.Equals(value) != true)) {
                    this.FLYER_IDField = value;
                    this.RaisePropertyChanged("FLYER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FLYER_IMAGE_URL {
            get {
                return this.FLYER_IMAGE_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.FLYER_IMAGE_URLField, value) != true)) {
                    this.FLYER_IMAGE_URLField = value;
                    this.RaisePropertyChanged("FLYER_IMAGE_URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FLYER_NAME_AR {
            get {
                return this.FLYER_NAME_ARField;
            }
            set {
                if ((object.ReferenceEquals(this.FLYER_NAME_ARField, value) != true)) {
                    this.FLYER_NAME_ARField = value;
                    this.RaisePropertyChanged("FLYER_NAME_AR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FLYER_NAME_EN {
            get {
                return this.FLYER_NAME_ENField;
            }
            set {
                if ((object.ReferenceEquals(this.FLYER_NAME_ENField, value) != true)) {
                    this.FLYER_NAME_ENField = value;
                    this.RaisePropertyChanged("FLYER_NAME_EN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> FRAME_ID {
            get {
                return this.FRAME_IDField;
            }
            set {
                if ((this.FRAME_IDField.Equals(value) != true)) {
                    this.FRAME_IDField = value;
                    this.RaisePropertyChanged("FRAME_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int OFFER_TYPE_ID {
            get {
                return this.OFFER_TYPE_IDField;
            }
            set {
                if ((this.OFFER_TYPE_IDField.Equals(value) != true)) {
                    this.OFFER_TYPE_IDField = value;
                    this.RaisePropertyChanged("OFFER_TYPE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int PROVIDER_ID {
            get {
                return this.PROVIDER_IDField;
            }
            set {
                if ((this.PROVIDER_IDField.Equals(value) != true)) {
                    this.PROVIDER_IDField = value;
                    this.RaisePropertyChanged("PROVIDER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int USER_ID {
            get {
                return this.USER_IDField;
            }
            set {
                if ((this.USER_IDField.Equals(value) != true)) {
                    this.USER_IDField = value;
                    this.RaisePropertyChanged("USER_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PRODUCT", Namespace="http://schemas.datacontract.org/2004/07/DataEntryDAL.DataAccessLogic")]
    [System.SerializableAttribute()]
    internal partial class PRODUCT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BRANCH_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DATE_FROMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DATE_TOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FLYER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MANUFACTURE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_ATTR_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_ATTR_10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_ATTR_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_ATTR_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_ATTR_4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_ATTR_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_ATTR_6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_ATTR_7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_ATTR_8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_ATTR_9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRODUCT_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_IMAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_NAME_ARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_NAME_ENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_PRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_TAGSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PROD_OFF_TYP_ATTR_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Parent_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TYPE_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> BRANCH_ID {
            get {
                return this.BRANCH_IDField;
            }
            set {
                if ((this.BRANCH_IDField.Equals(value) != true)) {
                    this.BRANCH_IDField = value;
                    this.RaisePropertyChanged("BRANCH_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> DATE_FROM {
            get {
                return this.DATE_FROMField;
            }
            set {
                if ((this.DATE_FROMField.Equals(value) != true)) {
                    this.DATE_FROMField = value;
                    this.RaisePropertyChanged("DATE_FROM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> DATE_TO {
            get {
                return this.DATE_TOField;
            }
            set {
                if ((this.DATE_TOField.Equals(value) != true)) {
                    this.DATE_TOField = value;
                    this.RaisePropertyChanged("DATE_TO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int FLYER_ID {
            get {
                return this.FLYER_IDField;
            }
            set {
                if ((this.FLYER_IDField.Equals(value) != true)) {
                    this.FLYER_IDField = value;
                    this.RaisePropertyChanged("FLYER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> MANUFACTURE_ID {
            get {
                return this.MANUFACTURE_IDField;
            }
            set {
                if ((this.MANUFACTURE_IDField.Equals(value) != true)) {
                    this.MANUFACTURE_IDField = value;
                    this.RaisePropertyChanged("MANUFACTURE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_ATTR_1 {
            get {
                return this.PRODUCT_ATTR_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_ATTR_1Field, value) != true)) {
                    this.PRODUCT_ATTR_1Field = value;
                    this.RaisePropertyChanged("PRODUCT_ATTR_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_ATTR_10 {
            get {
                return this.PRODUCT_ATTR_10Field;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_ATTR_10Field, value) != true)) {
                    this.PRODUCT_ATTR_10Field = value;
                    this.RaisePropertyChanged("PRODUCT_ATTR_10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_ATTR_2 {
            get {
                return this.PRODUCT_ATTR_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_ATTR_2Field, value) != true)) {
                    this.PRODUCT_ATTR_2Field = value;
                    this.RaisePropertyChanged("PRODUCT_ATTR_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_ATTR_3 {
            get {
                return this.PRODUCT_ATTR_3Field;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_ATTR_3Field, value) != true)) {
                    this.PRODUCT_ATTR_3Field = value;
                    this.RaisePropertyChanged("PRODUCT_ATTR_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_ATTR_4 {
            get {
                return this.PRODUCT_ATTR_4Field;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_ATTR_4Field, value) != true)) {
                    this.PRODUCT_ATTR_4Field = value;
                    this.RaisePropertyChanged("PRODUCT_ATTR_4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_ATTR_5 {
            get {
                return this.PRODUCT_ATTR_5Field;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_ATTR_5Field, value) != true)) {
                    this.PRODUCT_ATTR_5Field = value;
                    this.RaisePropertyChanged("PRODUCT_ATTR_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_ATTR_6 {
            get {
                return this.PRODUCT_ATTR_6Field;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_ATTR_6Field, value) != true)) {
                    this.PRODUCT_ATTR_6Field = value;
                    this.RaisePropertyChanged("PRODUCT_ATTR_6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_ATTR_7 {
            get {
                return this.PRODUCT_ATTR_7Field;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_ATTR_7Field, value) != true)) {
                    this.PRODUCT_ATTR_7Field = value;
                    this.RaisePropertyChanged("PRODUCT_ATTR_7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_ATTR_8 {
            get {
                return this.PRODUCT_ATTR_8Field;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_ATTR_8Field, value) != true)) {
                    this.PRODUCT_ATTR_8Field = value;
                    this.RaisePropertyChanged("PRODUCT_ATTR_8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_ATTR_9 {
            get {
                return this.PRODUCT_ATTR_9Field;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_ATTR_9Field, value) != true)) {
                    this.PRODUCT_ATTR_9Field = value;
                    this.RaisePropertyChanged("PRODUCT_ATTR_9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int PRODUCT_ID {
            get {
                return this.PRODUCT_IDField;
            }
            set {
                if ((this.PRODUCT_IDField.Equals(value) != true)) {
                    this.PRODUCT_IDField = value;
                    this.RaisePropertyChanged("PRODUCT_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_IMAGE {
            get {
                return this.PRODUCT_IMAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_IMAGEField, value) != true)) {
                    this.PRODUCT_IMAGEField = value;
                    this.RaisePropertyChanged("PRODUCT_IMAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_NAME_AR {
            get {
                return this.PRODUCT_NAME_ARField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_NAME_ARField, value) != true)) {
                    this.PRODUCT_NAME_ARField = value;
                    this.RaisePropertyChanged("PRODUCT_NAME_AR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_NAME_EN {
            get {
                return this.PRODUCT_NAME_ENField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_NAME_ENField, value) != true)) {
                    this.PRODUCT_NAME_ENField = value;
                    this.RaisePropertyChanged("PRODUCT_NAME_EN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_PRICE {
            get {
                return this.PRODUCT_PRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_PRICEField, value) != true)) {
                    this.PRODUCT_PRICEField = value;
                    this.RaisePropertyChanged("PRODUCT_PRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PRODUCT_TAGS {
            get {
                return this.PRODUCT_TAGSField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_TAGSField, value) != true)) {
                    this.PRODUCT_TAGSField = value;
                    this.RaisePropertyChanged("PRODUCT_TAGS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> PROD_OFF_TYP_ATTR_ID {
            get {
                return this.PROD_OFF_TYP_ATTR_IDField;
            }
            set {
                if ((this.PROD_OFF_TYP_ATTR_IDField.Equals(value) != true)) {
                    this.PROD_OFF_TYP_ATTR_IDField = value;
                    this.RaisePropertyChanged("PROD_OFF_TYP_ATTR_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> Parent_ID {
            get {
                return this.Parent_IDField;
            }
            set {
                if ((this.Parent_IDField.Equals(value) != true)) {
                    this.Parent_IDField = value;
                    this.RaisePropertyChanged("Parent_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int TYPE_ID {
            get {
                return this.TYPE_IDField;
            }
            set {
                if ((this.TYPE_IDField.Equals(value) != true)) {
                    this.TYPE_IDField = value;
                    this.RaisePropertyChanged("TYPE_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PROD_TYPE_SPEC", Namespace="http://schemas.datacontract.org/2004/07/DataEntryDAL.DataAccessLogic")]
    [System.SerializableAttribute()]
    internal partial class PROD_TYPE_SPEC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PRODUCT_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TEMPLATE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEMPLATE_VALUEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TYPE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TYPE_SPECS_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> PRODUCT_ID {
            get {
                return this.PRODUCT_IDField;
            }
            set {
                if ((this.PRODUCT_IDField.Equals(value) != true)) {
                    this.PRODUCT_IDField = value;
                    this.RaisePropertyChanged("PRODUCT_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> TEMPLATE_ID {
            get {
                return this.TEMPLATE_IDField;
            }
            set {
                if ((this.TEMPLATE_IDField.Equals(value) != true)) {
                    this.TEMPLATE_IDField = value;
                    this.RaisePropertyChanged("TEMPLATE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TEMPLATE_VALUE {
            get {
                return this.TEMPLATE_VALUEField;
            }
            set {
                if ((object.ReferenceEquals(this.TEMPLATE_VALUEField, value) != true)) {
                    this.TEMPLATE_VALUEField = value;
                    this.RaisePropertyChanged("TEMPLATE_VALUE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> TYPE_ID {
            get {
                return this.TYPE_IDField;
            }
            set {
                if ((this.TYPE_IDField.Equals(value) != true)) {
                    this.TYPE_IDField = value;
                    this.RaisePropertyChanged("TYPE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int TYPE_SPECS_ID {
            get {
                return this.TYPE_SPECS_IDField;
            }
            set {
                if ((this.TYPE_SPECS_IDField.Equals(value) != true)) {
                    this.TYPE_SPECS_IDField = value;
                    this.RaisePropertyChanged("TYPE_SPECS_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PROD_OFF_TYP_ATTR", Namespace="http://schemas.datacontract.org/2004/07/DataEntryDAL.DataAccessLogic")]
    [System.SerializableAttribute()]
    internal partial class PROD_OFF_TYP_ATTR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PROD_OFF_TYPE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_OFF_TYP_ATTR_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_OFF_TYP_ATTR_10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_OFF_TYP_ATTR_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_OFF_TYP_ATTR_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_OFF_TYP_ATTR_4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_OFF_TYP_ATTR_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_OFF_TYP_ATTR_6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_OFF_TYP_ATTR_7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_OFF_TYP_ATTR_8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_OFF_TYP_ATTR_9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PROD_OFF_TYP_ATTR_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> PROD_OFF_TYPE_ID {
            get {
                return this.PROD_OFF_TYPE_IDField;
            }
            set {
                if ((this.PROD_OFF_TYPE_IDField.Equals(value) != true)) {
                    this.PROD_OFF_TYPE_IDField = value;
                    this.RaisePropertyChanged("PROD_OFF_TYPE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PROD_OFF_TYP_ATTR_1 {
            get {
                return this.PROD_OFF_TYP_ATTR_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_OFF_TYP_ATTR_1Field, value) != true)) {
                    this.PROD_OFF_TYP_ATTR_1Field = value;
                    this.RaisePropertyChanged("PROD_OFF_TYP_ATTR_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PROD_OFF_TYP_ATTR_10 {
            get {
                return this.PROD_OFF_TYP_ATTR_10Field;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_OFF_TYP_ATTR_10Field, value) != true)) {
                    this.PROD_OFF_TYP_ATTR_10Field = value;
                    this.RaisePropertyChanged("PROD_OFF_TYP_ATTR_10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PROD_OFF_TYP_ATTR_2 {
            get {
                return this.PROD_OFF_TYP_ATTR_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_OFF_TYP_ATTR_2Field, value) != true)) {
                    this.PROD_OFF_TYP_ATTR_2Field = value;
                    this.RaisePropertyChanged("PROD_OFF_TYP_ATTR_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PROD_OFF_TYP_ATTR_3 {
            get {
                return this.PROD_OFF_TYP_ATTR_3Field;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_OFF_TYP_ATTR_3Field, value) != true)) {
                    this.PROD_OFF_TYP_ATTR_3Field = value;
                    this.RaisePropertyChanged("PROD_OFF_TYP_ATTR_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PROD_OFF_TYP_ATTR_4 {
            get {
                return this.PROD_OFF_TYP_ATTR_4Field;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_OFF_TYP_ATTR_4Field, value) != true)) {
                    this.PROD_OFF_TYP_ATTR_4Field = value;
                    this.RaisePropertyChanged("PROD_OFF_TYP_ATTR_4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PROD_OFF_TYP_ATTR_5 {
            get {
                return this.PROD_OFF_TYP_ATTR_5Field;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_OFF_TYP_ATTR_5Field, value) != true)) {
                    this.PROD_OFF_TYP_ATTR_5Field = value;
                    this.RaisePropertyChanged("PROD_OFF_TYP_ATTR_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PROD_OFF_TYP_ATTR_6 {
            get {
                return this.PROD_OFF_TYP_ATTR_6Field;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_OFF_TYP_ATTR_6Field, value) != true)) {
                    this.PROD_OFF_TYP_ATTR_6Field = value;
                    this.RaisePropertyChanged("PROD_OFF_TYP_ATTR_6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PROD_OFF_TYP_ATTR_7 {
            get {
                return this.PROD_OFF_TYP_ATTR_7Field;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_OFF_TYP_ATTR_7Field, value) != true)) {
                    this.PROD_OFF_TYP_ATTR_7Field = value;
                    this.RaisePropertyChanged("PROD_OFF_TYP_ATTR_7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PROD_OFF_TYP_ATTR_8 {
            get {
                return this.PROD_OFF_TYP_ATTR_8Field;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_OFF_TYP_ATTR_8Field, value) != true)) {
                    this.PROD_OFF_TYP_ATTR_8Field = value;
                    this.RaisePropertyChanged("PROD_OFF_TYP_ATTR_8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PROD_OFF_TYP_ATTR_9 {
            get {
                return this.PROD_OFF_TYP_ATTR_9Field;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_OFF_TYP_ATTR_9Field, value) != true)) {
                    this.PROD_OFF_TYP_ATTR_9Field = value;
                    this.RaisePropertyChanged("PROD_OFF_TYP_ATTR_9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int PROD_OFF_TYP_ATTR_ID {
            get {
                return this.PROD_OFF_TYP_ATTR_IDField;
            }
            set {
                if ((this.PROD_OFF_TYP_ATTR_IDField.Equals(value) != true)) {
                    this.PROD_OFF_TYP_ATTR_IDField = value;
                    this.RaisePropertyChanged("PROD_OFF_TYP_ATTR_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/DataEntryDAL.DataAccessLogic")]
    [System.SerializableAttribute()]
    internal partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int USER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_PAGESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_PASSWORDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_TYPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int USER_ID {
            get {
                return this.USER_IDField;
            }
            set {
                if ((this.USER_IDField.Equals(value) != true)) {
                    this.USER_IDField = value;
                    this.RaisePropertyChanged("USER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string USER_NAME {
            get {
                return this.USER_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_NAMEField, value) != true)) {
                    this.USER_NAMEField = value;
                    this.RaisePropertyChanged("USER_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string USER_PAGES {
            get {
                return this.USER_PAGESField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_PAGESField, value) != true)) {
                    this.USER_PAGESField = value;
                    this.RaisePropertyChanged("USER_PAGES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string USER_PASSWORD {
            get {
                return this.USER_PASSWORDField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_PASSWORDField, value) != true)) {
                    this.USER_PASSWORDField = value;
                    this.RaisePropertyChanged("USER_PASSWORD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string USER_TYPE {
            get {
                return this.USER_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_TYPEField, value) != true)) {
                    this.USER_TYPEField = value;
                    this.RaisePropertyChanged("USER_TYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    internal interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkLogin", ReplyAction="http://tempuri.org/IService1/checkLoginResponse")]
        string checkLogin(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkLogin", ReplyAction="http://tempuri.org/IService1/checkLoginResponse")]
        System.Threading.Tasks.Task<string> checkLoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllFlyers", ReplyAction="http://tempuri.org/IService1/getAllFlyersResponse")]
        string getAllFlyers(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllFlyers", ReplyAction="http://tempuri.org/IService1/getAllFlyersResponse")]
        System.Threading.Tasks.Task<string> getAllFlyersAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProviders", ReplyAction="http://tempuri.org/IService1/getAllProvidersResponse")]
        string getAllProviders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProviders", ReplyAction="http://tempuri.org/IService1/getAllProvidersResponse")]
        System.Threading.Tasks.Task<string> getAllProvidersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllOfferTypes", ReplyAction="http://tempuri.org/IService1/getAllOfferTypesResponse")]
        string getAllOfferTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllOfferTypes", ReplyAction="http://tempuri.org/IService1/getAllOfferTypesResponse")]
        System.Threading.Tasks.Task<string> getAllOfferTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllTimeFrames", ReplyAction="http://tempuri.org/IService1/getAllTimeFramesResponse")]
        string getAllTimeFrames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllTimeFrames", ReplyAction="http://tempuri.org/IService1/getAllTimeFramesResponse")]
        System.Threading.Tasks.Task<string> getAllTimeFramesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addNewFlyerBasicData", ReplyAction="http://tempuri.org/IService1/addNewFlyerBasicDataResponse")]
        string addNewFlyerBasicData(DataEntryApp.ServiceReference1.OFFER_FLYER flyer, string action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addNewFlyerBasicData", ReplyAction="http://tempuri.org/IService1/addNewFlyerBasicDataResponse")]
        System.Threading.Tasks.Task<string> addNewFlyerBasicDataAsync(DataEntryApp.ServiceReference1.OFFER_FLYER flyer, string action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductCategories", ReplyAction="http://tempuri.org/IService1/getAllProductCategoriesResponse")]
        string getAllProductCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductCategories", ReplyAction="http://tempuri.org/IService1/getAllProductCategoriesResponse")]
        System.Threading.Tasks.Task<string> getAllProductCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllCategoryTypes", ReplyAction="http://tempuri.org/IService1/getAllCategoryTypesResponse")]
        string getAllCategoryTypes(int categoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllCategoryTypes", ReplyAction="http://tempuri.org/IService1/getAllCategoryTypesResponse")]
        System.Threading.Tasks.Task<string> getAllCategoryTypesAsync(int categoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/submitFlyerProduct", ReplyAction="http://tempuri.org/IService1/submitFlyerProductResponse")]
        string submitFlyerProduct(DataEntryApp.ServiceReference1.PRODUCT product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/submitFlyerProduct", ReplyAction="http://tempuri.org/IService1/submitFlyerProductResponse")]
        System.Threading.Tasks.Task<string> submitFlyerProductAsync(DataEntryApp.ServiceReference1.PRODUCT product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/submitFlyerAllProducts", ReplyAction="http://tempuri.org/IService1/submitFlyerAllProductsResponse")]
        string submitFlyerAllProducts(DataEntryApp.ServiceReference1.PRODUCT[] products, DataEntryApp.ServiceReference1.PROD_TYPE_SPEC[][] allSpecs, DataEntryApp.ServiceReference1.PROD_OFF_TYP_ATTR[] allOfferTypes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/submitFlyerAllProducts", ReplyAction="http://tempuri.org/IService1/submitFlyerAllProductsResponse")]
        System.Threading.Tasks.Task<string> submitFlyerAllProductsAsync(DataEntryApp.ServiceReference1.PRODUCT[] products, DataEntryApp.ServiceReference1.PROD_TYPE_SPEC[][] allSpecs, DataEntryApp.ServiceReference1.PROD_OFF_TYP_ATTR[] allOfferTypes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFlyerBasicData", ReplyAction="http://tempuri.org/IService1/getFlyerBasicDataResponse")]
        string getFlyerBasicData(int flyerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFlyerBasicData", ReplyAction="http://tempuri.org/IService1/getFlyerBasicDataResponse")]
        System.Threading.Tasks.Task<string> getFlyerBasicDataAsync(int flyerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFlyerProducts", ReplyAction="http://tempuri.org/IService1/getFlyerProductsResponse")]
        string getFlyerProducts(int flyerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFlyerProducts", ReplyAction="http://tempuri.org/IService1/getFlyerProductsResponse")]
        System.Threading.Tasks.Task<string> getFlyerProductsAsync(int flyerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteFlyerAndProductsByID", ReplyAction="http://tempuri.org/IService1/deleteFlyerAndProductsByIDResponse")]
        string deleteFlyerAndProductsByID(int flyerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteFlyerAndProductsByID", ReplyAction="http://tempuri.org/IService1/deleteFlyerAndProductsByIDResponse")]
        System.Threading.Tasks.Task<string> deleteFlyerAndProductsByIDAsync(int flyerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateUserPassword", ReplyAction="http://tempuri.org/IService1/updateUserPasswordResponse")]
        string updateUserPassword(int userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateUserPassword", ReplyAction="http://tempuri.org/IService1/updateUserPasswordResponse")]
        System.Threading.Tasks.Task<string> updateUserPasswordAsync(int userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/approveRejectFlyer", ReplyAction="http://tempuri.org/IService1/approveRejectFlyerResponse")]
        string approveRejectFlyer(int flyerID, bool approveRejectFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/approveRejectFlyer", ReplyAction="http://tempuri.org/IService1/approveRejectFlyerResponse")]
        System.Threading.Tasks.Task<string> approveRejectFlyerAsync(int flyerID, bool approveRejectFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getListOfAllUsers", ReplyAction="http://tempuri.org/IService1/getListOfAllUsersResponse")]
        string getListOfAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getListOfAllUsers", ReplyAction="http://tempuri.org/IService1/getListOfAllUsersResponse")]
        System.Threading.Tasks.Task<string> getListOfAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addNewUser", ReplyAction="http://tempuri.org/IService1/addNewUserResponse")]
        string addNewUser(DataEntryApp.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addNewUser", ReplyAction="http://tempuri.org/IService1/addNewUserResponse")]
        System.Threading.Tasks.Task<string> addNewUserAsync(DataEntryApp.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductManufactures", ReplyAction="http://tempuri.org/IService1/getAllProductManufacturesResponse")]
        string getAllProductManufactures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductManufactures", ReplyAction="http://tempuri.org/IService1/getAllProductManufacturesResponse")]
        System.Threading.Tasks.Task<string> getAllProductManufacturesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductBranches", ReplyAction="http://tempuri.org/IService1/getAllProductBranchesResponse")]
        string getAllProductBranches(int parentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductBranches", ReplyAction="http://tempuri.org/IService1/getAllProductBranchesResponse")]
        System.Threading.Tasks.Task<string> getAllProductBranchesAsync(int parentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTypeAllSpecs", ReplyAction="http://tempuri.org/IService1/getTypeAllSpecsResponse")]
        string getTypeAllSpecs(int typeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTypeAllSpecs", ReplyAction="http://tempuri.org/IService1/getTypeAllSpecsResponse")]
        System.Threading.Tasks.Task<string> getTypeAllSpecsAsync(int typeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductOfferTypes", ReplyAction="http://tempuri.org/IService1/getAllProductOfferTypesResponse")]
        string getAllProductOfferTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductOfferTypes", ReplyAction="http://tempuri.org/IService1/getAllProductOfferTypesResponse")]
        System.Threading.Tasks.Task<string> getAllProductOfferTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/submitAllProducts", ReplyAction="http://tempuri.org/IService1/submitAllProductsResponse")]
        string submitAllProducts(string productsListSTR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/submitAllProducts", ReplyAction="http://tempuri.org/IService1/submitAllProductsResponse")]
        System.Threading.Tasks.Task<string> submitAllProductsAsync(string productsListSTR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductsList", ReplyAction="http://tempuri.org/IService1/getAllProductsListResponse")]
        string getAllProductsList(int flyerID, int parentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductsList", ReplyAction="http://tempuri.org/IService1/getAllProductsListResponse")]
        System.Threading.Tasks.Task<string> getAllProductsListAsync(int flyerID, int parentID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IService1Channel : DataEntryApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class Service1Client : System.ServiceModel.ClientBase<DataEntryApp.ServiceReference1.IService1>, DataEntryApp.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string checkLogin(string userName, string password) {
            return base.Channel.checkLogin(userName, password);
        }
        
        public System.Threading.Tasks.Task<string> checkLoginAsync(string userName, string password) {
            return base.Channel.checkLoginAsync(userName, password);
        }
        
        public string getAllFlyers(int userID) {
            return base.Channel.getAllFlyers(userID);
        }
        
        public System.Threading.Tasks.Task<string> getAllFlyersAsync(int userID) {
            return base.Channel.getAllFlyersAsync(userID);
        }
        
        public string getAllProviders() {
            return base.Channel.getAllProviders();
        }
        
        public System.Threading.Tasks.Task<string> getAllProvidersAsync() {
            return base.Channel.getAllProvidersAsync();
        }
        
        public string getAllOfferTypes() {
            return base.Channel.getAllOfferTypes();
        }
        
        public System.Threading.Tasks.Task<string> getAllOfferTypesAsync() {
            return base.Channel.getAllOfferTypesAsync();
        }
        
        public string getAllTimeFrames() {
            return base.Channel.getAllTimeFrames();
        }
        
        public System.Threading.Tasks.Task<string> getAllTimeFramesAsync() {
            return base.Channel.getAllTimeFramesAsync();
        }
        
        public string addNewFlyerBasicData(DataEntryApp.ServiceReference1.OFFER_FLYER flyer, string action) {
            return base.Channel.addNewFlyerBasicData(flyer, action);
        }
        
        public System.Threading.Tasks.Task<string> addNewFlyerBasicDataAsync(DataEntryApp.ServiceReference1.OFFER_FLYER flyer, string action) {
            return base.Channel.addNewFlyerBasicDataAsync(flyer, action);
        }
        
        public string getAllProductCategories() {
            return base.Channel.getAllProductCategories();
        }
        
        public System.Threading.Tasks.Task<string> getAllProductCategoriesAsync() {
            return base.Channel.getAllProductCategoriesAsync();
        }
        
        public string getAllCategoryTypes(int categoryID) {
            return base.Channel.getAllCategoryTypes(categoryID);
        }
        
        public System.Threading.Tasks.Task<string> getAllCategoryTypesAsync(int categoryID) {
            return base.Channel.getAllCategoryTypesAsync(categoryID);
        }
        
        public string submitFlyerProduct(DataEntryApp.ServiceReference1.PRODUCT product) {
            return base.Channel.submitFlyerProduct(product);
        }
        
        public System.Threading.Tasks.Task<string> submitFlyerProductAsync(DataEntryApp.ServiceReference1.PRODUCT product) {
            return base.Channel.submitFlyerProductAsync(product);
        }
        
        public string submitFlyerAllProducts(DataEntryApp.ServiceReference1.PRODUCT[] products, DataEntryApp.ServiceReference1.PROD_TYPE_SPEC[][] allSpecs, DataEntryApp.ServiceReference1.PROD_OFF_TYP_ATTR[] allOfferTypes) {
            return base.Channel.submitFlyerAllProducts(products, allSpecs, allOfferTypes);
        }
        
        public System.Threading.Tasks.Task<string> submitFlyerAllProductsAsync(DataEntryApp.ServiceReference1.PRODUCT[] products, DataEntryApp.ServiceReference1.PROD_TYPE_SPEC[][] allSpecs, DataEntryApp.ServiceReference1.PROD_OFF_TYP_ATTR[] allOfferTypes) {
            return base.Channel.submitFlyerAllProductsAsync(products, allSpecs, allOfferTypes);
        }
        
        public string getFlyerBasicData(int flyerID) {
            return base.Channel.getFlyerBasicData(flyerID);
        }
        
        public System.Threading.Tasks.Task<string> getFlyerBasicDataAsync(int flyerID) {
            return base.Channel.getFlyerBasicDataAsync(flyerID);
        }
        
        public string getFlyerProducts(int flyerID) {
            return base.Channel.getFlyerProducts(flyerID);
        }
        
        public System.Threading.Tasks.Task<string> getFlyerProductsAsync(int flyerID) {
            return base.Channel.getFlyerProductsAsync(flyerID);
        }
        
        public string deleteFlyerAndProductsByID(int flyerID) {
            return base.Channel.deleteFlyerAndProductsByID(flyerID);
        }
        
        public System.Threading.Tasks.Task<string> deleteFlyerAndProductsByIDAsync(int flyerID) {
            return base.Channel.deleteFlyerAndProductsByIDAsync(flyerID);
        }
        
        public string updateUserPassword(int userID, string password) {
            return base.Channel.updateUserPassword(userID, password);
        }
        
        public System.Threading.Tasks.Task<string> updateUserPasswordAsync(int userID, string password) {
            return base.Channel.updateUserPasswordAsync(userID, password);
        }
        
        public string approveRejectFlyer(int flyerID, bool approveRejectFlag) {
            return base.Channel.approveRejectFlyer(flyerID, approveRejectFlag);
        }
        
        public System.Threading.Tasks.Task<string> approveRejectFlyerAsync(int flyerID, bool approveRejectFlag) {
            return base.Channel.approveRejectFlyerAsync(flyerID, approveRejectFlag);
        }
        
        public string getListOfAllUsers() {
            return base.Channel.getListOfAllUsers();
        }
        
        public System.Threading.Tasks.Task<string> getListOfAllUsersAsync() {
            return base.Channel.getListOfAllUsersAsync();
        }
        
        public string addNewUser(DataEntryApp.ServiceReference1.User user) {
            return base.Channel.addNewUser(user);
        }
        
        public System.Threading.Tasks.Task<string> addNewUserAsync(DataEntryApp.ServiceReference1.User user) {
            return base.Channel.addNewUserAsync(user);
        }
        
        public string getAllProductManufactures() {
            return base.Channel.getAllProductManufactures();
        }
        
        public System.Threading.Tasks.Task<string> getAllProductManufacturesAsync() {
            return base.Channel.getAllProductManufacturesAsync();
        }
        
        public string getAllProductBranches(int parentID) {
            return base.Channel.getAllProductBranches(parentID);
        }
        
        public System.Threading.Tasks.Task<string> getAllProductBranchesAsync(int parentID) {
            return base.Channel.getAllProductBranchesAsync(parentID);
        }
        
        public string getTypeAllSpecs(int typeID) {
            return base.Channel.getTypeAllSpecs(typeID);
        }
        
        public System.Threading.Tasks.Task<string> getTypeAllSpecsAsync(int typeID) {
            return base.Channel.getTypeAllSpecsAsync(typeID);
        }
        
        public string getAllProductOfferTypes() {
            return base.Channel.getAllProductOfferTypes();
        }
        
        public System.Threading.Tasks.Task<string> getAllProductOfferTypesAsync() {
            return base.Channel.getAllProductOfferTypesAsync();
        }
        
        public string submitAllProducts(string productsListSTR) {
            return base.Channel.submitAllProducts(productsListSTR);
        }
        
        public System.Threading.Tasks.Task<string> submitAllProductsAsync(string productsListSTR) {
            return base.Channel.submitAllProductsAsync(productsListSTR);
        }
        
        public string getAllProductsList(int flyerID, int parentID) {
            return base.Channel.getAllProductsList(flyerID, parentID);
        }
        
        public System.Threading.Tasks.Task<string> getAllProductsListAsync(int flyerID, int parentID) {
            return base.Channel.getAllProductsListAsync(flyerID, parentID);
        }
    }
}
